---
title: "Lesson Plan"
description: " "
date: "January 1, 2026"
date-modified: "last-modified"
format: html
editor: visual
---

| Lesson | Date | Venue | Topic | Remark |
|---------------|:--------------|---------------|:--------------|---------------|
| 1 | 18/4 | SOE/SCIS2 SR 5-2 | [Introduction to Visual Analytics](outline/Lesson01_outline.html) |  |
| 2 | 25/4 | SOE/SCIS2 SR 5-2 | [Designing Graphs to Enlighten](outline/Lesson02_outline.html) |  |
| 3 | 2/5 | SOSS/CIS Seminar Room 1-1 | [Interactivity in Visual Analytics](outline/Lesson03_outline.html) |  |
| 4 | 9/5 | SOSS/CIS Seminar Room B1-1 | [Fundamentals of Visual Analytics](outline/Lesson04_outline.html) |  |
| 5 | 16/5 | SOSS/CIS Seminar Room B1-1 | [Visual Multivariate Analysis](outline/Lesson05_outline.html) |  |
| 6 | 23/5 | SOSS/CIS Seminar Room B1-1 | [Designing Web-enabled Visual Analytics Application with Shiny](outline/Lesson06_outline.html) |  |
|  | 30/5 |  |  | Recess |
| 7 | 6/6 | SOSS/CIS Seminar Room B1-1 | [Visualising and Analysing Time-Oriented Data](outline/Lesson07_outline.html) |  |
| 8 | 13/6 | SOE/SCIS2 Seminar Room B1-1 | [Visualising and Analysing Geographic Data](outline/Lesson08_outline.html) |  |
| 9 | 20/6 | SOSS/CIS Seminar Room B1-1 | [Visualising and Analysing Network Data](outline/Lesson09_outline.html) |  |
| 10 | 27/6 | SOSS/CIS Seminar Room B1-1 | [Information Dashboard Design](outline/Lesson10_outline.html) |  |
| 11 | 4/7 | TBC | Poster Presentation | VA Project due 5th July 2026 |
