---
title: "Take-home Exercise 1"
date: "May 6, 2026"
date-modified: "last modified"
---

Visual analytics is a field that emerged around 2005 (Thomas and Cook, 2006) motivated by the need to analyze increasingly large and complex data. Data is also often time-dependent, has some quality problems, such as noise, outliers, duplicate entries, and missing values. An appropriate analysis of such data requires more than a straightforward visualization. Also, hypothesis-based statistical analysis or data mining in isolation are not promising. Visual analytics is an interdisciplinary process, where data visualization, statistics, and data mining is combined and steered by an analyst by means of appropriate visual interfaces. This integration is motivated by the attempt to combine human strengths, such as judgment and recognition of patterns, with the strengths of automatic data processing. 

Difference from visualization  Visual analytics serves as an interface between humans and computers, providing (interactive) data representations to the user on demand. Such approaches can be used to understand data, to confirm or reject hypotheses, and to discover new knowledge. Therefore visual analytics and visualization primarily differ by the aim: the former supports analytical tasks or advances knowledge through interactive visual methods that make use of other interdisciplinary approaches (such as machine learning), whereas the latter represents data graphically. Additionally, the two fields differ in terms of employed strategies: visual analytics heavily supports the interplay between human and machine and provides a junction between automated analysis techniques, visualization, and human-computer interaction. Here, the user–analyst is the most significant component, as they steer the entire process.

