---
title: "Take-home Exercise 2"
date: "May 5, 2025"
date-modified: "last-modified"
format: html
editor: visual
---

## The Task

In this take-home exercise, you are required to select **one** of the topic below and provide solutions to the challenge:

- [Mini-Challenge 1](https://vast-challenge.github.io/2026/MC1.html):Your job is to dig into TenantThread’s internal communications from the two weeks leading up to the breach and reconstruct what was going. You have information from AI agents that managed TenantThread’s corporate communications. This includes the messages, internal deliberations, and public post. Build a visual analytics system to help determine: **Did TenantThread’s team deliberately leak the merger or did the system simply break down under pressure?**
- [Mini-Challenge 2](https://vast-challenge.github.io/2026/MC2.html): You work in the AI systems administration department of Company A. A post was recently made on SaidIT looks like a malfunction of an agent: It is in gibberish and in a forum that appears random. Your job is to track down why this post occurred and suggest a remedy to the situation by building a visual analytics system that integrates visuals with algorithms to enable interactive exploration and documentation of the multi-agent system!

::: callout-important
- You only need to attempt either **one out of the two Mini Cases**
- The data should be processed by using appropriate **tidyverse** family of packages and the Visual Analytics tools must be prepared by using appropriate R packages.
:::

## Assessment Rubric

- Quality of Visual Storytelling (30%): Ability to provide visually-driven discussions and answers on the tasks and questions chosen.
- Quality of Data Visualisation (30%): Appropriateness, functional and aesthetics of the data visualisation used.
- Quality of Data Preparation and Wrangling (20%): Appropriateness and proficiency of using tidyverse and other related R packages to prepare and wrangle the data.
- Quality of Reproducibility (20%): Completeness and comprehensiveness of documenting the data visualisation process including and not limited to data import, data preparation, data wrangling, data integration and data visualisation design.

## Submission Instructions

This is an individual assignment. You are required to work on the take-home exercises and prepare submission individually.

::: callout-important
The specific submission instructions are as follows:

- The write-up of the take-home exercise must be in **Quarto html document** format. You are required to publish the write-up on [**Vercel**](https://https://vercel.com/).
:::

## Submission date

Your completed take-home exercise is due on **7th June 2026, by 11:59 mid-night**.

## KickStarter

## Learning from Senior

- [ISSS608 2016-17 T3 Assign GUAN YIFEI](https://visualdata.wustl.edu/varepository/VAST_Challenge_2017/challenges/Mini-Challenge_1/entries/Singapore_Management_University_-_Yifei/). Although this assignment was completed by using Tableau Professional but there are a lot we can learn from the submission especially the discussion of visual insights.
- [ISSS608 2016-17 T3 Assign ZHANG YANRONG](https://visualdata.wustl.edu/varepository/VAST_Challenge_2017/challenges/Grand_Challenge/entries/Singapore_Management_University/). Although this assignment was completed by using QGIS and Tableau Professional but there are a lot we can learn from the submission especially the discussion of visual insights.
- [ISSS608 2021-22 April Term Assignment 6: Ong Zhi Rong Jordan](https://isss608-jordan-va.netlify.app/th_ex6/th_ex6.html)
- [ISSS608 2021-22 April Term Assignment 6: Raunak Kapur](https://isss608-raunakkapur.netlify.app/th_ex/the6)

**AY2022-23 April Term**

- [ONG CHAE HUI](https://smu-isss608-vaa.netlify.app/take-home_ex/take-home_ex03/take-home_ex03#overview)
- [KWA KAH BOON](https://cosmic-boon.netlify.app/take-home_ex/take-home_ex03/take-home_ex3)
- [FONG BAO XIAN](https://fongbx-isss608-visual-analytics.netlify.app/take-home%20ex/take-home_ex03/take-home_ex03)
- [HAILEY CHEONG SZE-YENN](https://isss608-ay2023-haileycsy.netlify.app/take-home_ex/take-home_ex03/take-home_ex03)

**AY2023-24 April Term**

- [Kristine Joy Paas](https://isss608-kjcpaas.netlify.app/take-home_exs/ex3/take-home_ex3)
- [Seng Jing Yi](https://jingyi-vaa.netlify.app/take-home_ex/take-home_ex03/take-home_ex03_eda)

## Reference

- [Analysis Without Data: Teaching Students to Tackle the VAST Challenge](https://par.nsf.gov/servlets/purl/10394301)
